name: Simple CI Demo

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      input:
        type: string
        required: true


jobs: 
    job-without-environment:
        runs-on: ubuntu-22.04

        steps:
          - name: Print Secret
            run: echo "print secret var ${{secrets.DATABASE_URL}}"

          - name: Print Client
            run: echo "print secret var ${{vars.APP_URL}}"


    job-with-environment:
        runs-on: ubuntu-22.04

        steps:
          - name: Print Secret
                          
            run: echo "print secret var ${{secrets.GOOGLE_CLIENT_ID}}"

          - name: Print Client
            run: echo "print secret var ${{vars.APP_URL}}"

    job-uses-reusable-workflow: 
       permissions: 
        contents: write
        pull-requests: write

       uses: "yousefdawood7/github-actions-demo/.github/workflows/github-app.yaml@main"
       with:
         body: "@${{github.actor}} Test Test Test"
    
    email-test-job:
      runs-on: ubuntu-22.04


      steps:
        - name: Code Checkout
          uses: actions/checkout@v7

        - name: Setup Node
          uses: actions/setup-node@v7
          with:
            package-manager-cache: true
            node-version: 24

        - name: Setup Node Mailer
          run: npm i nodemailer

        - name: Run Custom Script
          env:
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_SECRET_ID }}
            GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          uses: actions/github-script@v9

          with: 
            script: |
              const script = require('./.github/scripts/script.js')
              script()