name: Simple CI Demo

on:
  push: 
    branches: 
        - main
        - master
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - development
          - production
        required: true
        default: development
        description: Choose environment that you going to deploy to


jobs: 
    job-without-environment:
        runs-on: ubuntu-22.04

        steps:
          - name: Print Secret
            run: echo "print secret var ${{secrets.DATABASE_URL}}"

          - name: Print Client
            run: echo "print secret var ${{vars.APP_URL}}"


    job-with-environment:
        runs-on: ubuntu-22.04

        steps:
          - name: Print Secret
                          
            run: echo "print secret var ${{secrets.GOOGLE_CLIENT_ID}}"

          - name: Print Client
            run: echo "print secret var ${{vars.APP_URL}}"

    job-list:
        runs-on: ubuntu-22.04

        steps: 
         - name: list directory
           run: ls