name: Simple CI Demo

on:
  push: 
    branches: 
        - main
        - master
  workflow_dispatch: 

jobs:
  os-printer-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: printing os
        run: echo i'm working on ${{ runner.os }}

  os-printer-windows:
    runs-on: windows-2025
    defaults:
      run:
        shell: bash
    steps:
      - name: printing os
        run: echo i'm working on ${{ runner.os }}
  