name: demonstrate closing workflow

on: 
    pull_request: 
        types: [closed]

jobs:
    printing-close:
        runs-on: ubuntu-22.04
        steps:
            - name: print close
              run: echo ${{ github.ref_name }} is ${{github.event.action}}