name: Demonstrate Dispatch Workflow
run-name: Demonstrate Dispatch in CI/CD

on: 
    workflow_dispatch: 
        inputs:
          debug:
            description: is this production ?!
            type: boolean
            default: false
            required: true


env: 
    MY_WORKFLOW_VAR: workflow
    MY_OVERWRITTEN_VAR: workflow

    

jobs:
    echo-data:
        runs-on: ubuntu-22.04
        steps:
            - name: echo Github Context
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "Ref Name: ${{ github.ref_name }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.repository_owner }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: print variable
              run: echo ${{ vars.MY_APP }}
    echo-dispatch:
        runs-on: ubuntu-22.04
        steps:
          - name: Dispatch Context
            run: echo ${{ inputs.debug }}
    echo-vars:
        env:
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR: job
        runs-on: ubuntu-22.04
        steps:
            - name: Variable ENVs
              env: 
                APP_TOP_SECRET: ${{ secrets.APP_SECRET }}
              run: |
                echo ${{ secrets.APP_SECRET }}
                echo ${{ env.APP_TOP_SECRET }}
             


