name: Demonstrate Dispatch Workflow
run-name: Demonstrate Dispatch in CI/CD

on: 
    workflow_dispatch: 
        inputs:
          debug:
            description: is this production ?!
            type: boolean
            default: false
            required: true


env: 
    MY_WORKFLOW_VAR: workflow
    MY_OVERWRITTEN_VAR: workflow

    

jobs:
  echo1:
    runs-on: ubuntu-22.04
    steps:
      - name: Failing Step
        run: sleep 20

      - name: I Will be Always
        if: always()
        run: |
          echo always
          sleep 10
        
        
      - name: I Will be Cancelled
        if: ${{ !cancelled() }}
        run: echo '!Cancelled'

      



