name: Event Filters and Activity Types

on: 
    pull_request: 
        types: [opened, synchronize]
        branches: 
            - main
    push: 
        branches: 
            - main

jobs:
    echo:
        runs-on: ubuntu-22.04
        steps:
            - name: printing event types
              run: echo Base branch is ${{ github.base_ref }} and event name ${{ github.event_name }}

