name: Github app notifications

on: 
    workflow_call: 
        inputs:
            body:
                type: string
                required: true
                
permissions: 
    contents: write
    pull-requests: write

jobs: 
    commit-comment: 
        runs-on: ubuntu-22.04
        
        steps:
            - uses: actions/github-script@v9
              env:
                  BODY: ${{ inputs.body }}

              with:
                script: | 
                    const payload = context.payload

                    if(payload.pull_request) {
                        github.rest.issues.createComment({
                            ...context.repo,
                            issue_number: context.issue.number,    
                            body: process.env.BODY
                        })
                        return;
                    }
                        
                    if(payload.commits && payload.commits.length > 0)  {
                        github.rest.repos.createCommitComment({
                            ...context.repo,
                            commit_sha: context.sha,
                            body: process.env.BODY
                        })
                    }




