name: Github app notifications

on: 
    push: 
        branches: [main]

    pull_request: 
        branches: [main] # base branch



permissions: 
    contents: write
    pull-requests: write
jobs: 
    commit-comment: 
        runs-on: ubuntu-22.04
        
        steps:
            - uses: actions/github-script@v9
              
              with:
                script: | 
                    const payload = context.payload

                    if(payload.pull_request) {
                        github.rest.issues.createComment({
                            ...context.repo,
                            issue_number: context.issue.number,    
                            body: `@${context.actor} what a great PR G`
                        })
                        return;
                    }
                        
                    if(payload.commits && payload.commits.length > 0)  {
                        github.rest.repos.createCommitComment({
                            ...context.repo,
                            commit_sha: context.sha,
                            body: `@${context.actor} what a great Commit G`
                        })
                    }




