name: CI CD MATRIX 


on: 
    push:
        branches: [main]
    workflow_dispatch: 


jobs:
    
    print-os-node-version:
        runs-on: ${{ matrix.os }}

        defaults:
            run:
                shell: bash
 
        strategy:
            matrix:
                os: ["ubuntu-latest", "windows-latest"]
                
        steps:
            - name: print os versions
              run: echo "${{ matrix.os }} ===> ${{ runner.os }}"                

