name: CI CD MATRIX 


on: 
    push:
        branches: [main]
    workflow_dispatch: 


jobs:
    
    print-os-node-version:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                os: ["yousef", "dawood"]
                version: [1, 2, 3 , 4, 5, 6]
                exclude:
                    - os: "yousef"
                      version: "1"


        steps:
            - name: print node versions
              run: echo "${{ matrix.version }} ==> ${{matrix.os}}"
                

