name: Test


on:
    workflow_dispatch: 
    push:
        branches:
            - main

jobs:
    get-bot-comment:
        runs-on: ubuntu-22.04

        steps:
            - name: checkout
              uses: actions/checkout@v7
            - name: bot
              uses: actions/github-script@v9
              with:
                script: |
                 const payload = context.payload
                 
                 if(payload.pull_request) {
                    github.rest.issues.createComment( {
                        issue_number: context.issue.number,
                        body: "Hello @yousefdawood7 How is it going"
                    }) 
                    }

                    const commitSha = payload.commits && payload.commits.length > 0
                    
                    github.rest.repos.createCommitComment({
                      ...context.repo,
                      commit_sha: context.sha,
                        body: "Hello @yousefdawood7 How is it going"
                    });






        

