name: Workflow Runners
on: push


jobs:
    show-os:
        runs-on: windows-latest
        steps: 
            - name: Windows step
              shell: bash
              run: echo Hello from Windows operating system   
              
            - name: Macos step
              run: echo Hello from Mac operating system   